### ISSUE TITLE
Training new models not working/ tensorflow 1 not available.

### ISSUE THREAD

**Issue by patsygreen** [ArthurFDLR/GANightSky#1]
Hello @ArthurFDLR ,

I used your code and changed it accordingly for my own project, it has helped me a lot. However, today I wanted to work again with the codes but google colab gave me a message that I can't use tensorflow 1 anymore, and thus the rest of the code for training the AI does not want to work anymore.

Do you have any idea how I can fix this? I tried just using tensorflow 2 but with both versions I get an error when I try to train a new model.

Thanks in advance!

**Comment by patsygreen** [comment]
<img width="1122" alt="Screenshot 2022-08-30 at 19 46 05" src="https://user-images.githubusercontent.com/112496247/187507328-cbb1bb0f-43d2-45b9-b42c-48a752aad5de.png">
<img width="1011" alt="Screenshot 2022-08-30 at 19 46 17" src="https://user-images.githubusercontent.com/112496247/187507333-e561b1e7-8221-4746-984d-d98b8dc4d8a4.png">

**Comment by ArthurFDLR** [comment]
Hey, thanks for raising this issue. Indeed, Google removed support for TensorFlow 1 earlier this month ([see releases notes](https://colab.research.google.com/notebooks/relnotes.ipynb#scrollTo=p8Hf89oCXY0_)). I've tried reinstalling TensorFlow 1 manually but encountered other dependencies issues.

The PyTorch implementation seems more stable, though. Hopefully, the API is the same between both implementations. It would only be a matter of switching the repo when downloading the model.

**Comment by patsygreen** [comment]
Thanks for the answer. 

Sorry, I never worked with PyTorch. How do I switch the repo? Is that before going into PyTorch or while coding in PyTorch?

**Comment by ArthurFDLR** [comment]
The switch isn't as straightforward as I expected. The API is slightly different and would need some work to get it working in the Notebook. However, Derrick Schultz has a great collection of Jupyter Notebooks to play with SG2-ADA in [his branch of the repo](https://github.com/dvschultz/stylegan2-ada-pytorch). They are based on the PyTorch implementation. This would be a good starting point: [SG2_ADA_PyTorch.ipynb](https://colab.research.google.com/github/dvschultz/stylegan2-ada-pytorch/blob/main/SG2_ADA_PyTorch.ipynb)

**Comment by patsygreen** [comment]
Thank you! 

I will explore those to fix my issues :)
